{% set name = "moment" %}
{% set version = "2.24.0" %}
{% set sha256 = "6159b769f2baa97e1ddbd172cc88d7726ca6c631155a54d98a40a007700ea780" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/moment/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g moment
  requires:
    - nodejs
   

about:
  home: https://github.com/moment/moment
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Parse, validate, manipulate, and display dates in javascript.'
  description: |
    A lightweight JavaScript date library for parsing, validating, manipulating, and formatting dates.   
  doc_url: http://momentjs.com/docs/
  dev_url: https://github.com/moment/moment

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
