travis:
  secure:
    BINSTAR_TOKEN: IprYvAKvMxOe4EQxvonNoHxc36MUlKGgLW4crbfGtIZWTdMzEmTXZAWLlAmicI1953pcEhf1T0YJVsBud4u89VX3kXqY7IzSUxcxBEL1soenSo+0B00HupQZ5XixD2+XFqkGZSZntIthVkXOGARfC3VyNWNF6CE4RlvB98ARMH7kMxjvXiW6j5gDyUBul/iEgFMeIPpns6jvxWeKuoTyyJhfq1lcUFGQpCiTiF2NOq7Dyr6JBph3zoUMBnKQGf+kO5x7YXY1OPjYA2Vhaa0zPseID2JO4OZUGhH7iXfehPCoOqkMUef9JBJrCcRyEJBjoYSShD/sIJIrGpMsbionnUt9BFMYU3owiYm/GAD3Jhpa7solyCrf2OBqZM4eTGkFq/8a2wGIMvRVuL5sC51fkKCikeY5QjJXwp3r9lcJt2gjgm7P0Qsa9hUAnQAmRo6xA6uh/J04oN0dZQR9zB3OwZOCBp17Dd6Anr7wtCZiNabX+YSjq64bGd5DlXom8J4kVAVYDAtAjP3fRRNoTYEZYpwBhgLe+u0cjrQdG1oEOeOX5Q0E1W+gS85uhtZh143S4FQhntEVsMR528DiTEZkpnQ8I+R0af8uEcwuodxAxIjhBziovN40RTI9PlEJIPut73VbyUv0VvW4EcoPaSOCZ8fTMQaoTC5IBBg1JOUqq7I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
