travis:
  secure:
    BINSTAR_TOKEN: LQjpSACScRBDCp9d3KWOYrIhPdWpFBdl8dsgVEw+h2Dm2ps6Qx7XpUwoR7r53LSK6WyaKRo9gY5dvpOGVsELE7UGNScMqoiGwuS50/wgno/iWZIEJOFQGb1rqzNdR4t1KeQV+azukR8nt03In5mlVL9GKP64WZ71ASo/Wb3N0Qt6rWvXxEeBuiJTu0GPrKhgKJMqsNDJzhlc1jMllxRPOg5ZoWCMQGjH61eSYpkAgTTah5VebX14jD2BLjCYX9Xu6ocQR2HvRH+SBdiGTpJ5/I4rxevAPhkyTx32S2WK4YhJPFPEQJJ06jSnC87KzyVTZ9RXFDdfU3l5iYcXyY1d9/hxng940zrj9tfgEeSwNKM5Oas6ohHpWIIoAsqLdRB3LSNR2tS6/Jzs1EvwvejFoOR9u/qvMh5ZCf6U/iDok8X9UxUkP15ZK++LmNlua+Ltaftc/lAGt6Bwag0Qn01jJdy4DKvJN7oWB3szBM+SF0vMCukIE8unAJDp6xR+1kHBUBTMLel4yM2BLYpWmGlKQdY3clh3wlQB9l3lSPE9u0Pg3MHMvNXUCbxe5ukY4BzvilRVQjEuQ/U/yjqrvii2Rh/mhFxjmUOyQp58G7JblUymr8/9vVYlrako2RTyWs/mQuvbIdrEPFsS9KhP/T4apcT2Kw33u7vCy+lcEHcYiB0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
